spring:
  application:
    name: NPlusOne Problem
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    driver-class-name:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
#      hibernate.default_batch_fetch_size: 1000
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.type: trace